=== hmcts/bulk-scan-processor/src/main/resources/metafile-schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "https://hmcts.github.io/bulk-scan-processor",
  "type": "object",
  "title": "Envelope schema",
  "properties": {
    "case_number": {
      "id": "#/properties/case_number",
      "type": "string",
      "title": "Case reference number to which the envelope belongs to"
    },
    "po_box": {
      "id": "#/properties/po_box",
      "type": "string",
      "title": "P.O. Box number on which the envelope was received"
    },
    "jurisdiction": {
      "id": "#/properties/jurisdiction",
      "type": "string",
      "title": "Name of the jurisdiction"
    },
    "delivery_date": {
      "id": "#/properties/delivery_date",
      "type": "string",
      "title": "Date time in UTC for when the package was delivered at the bulk scanning supplier",
      "pattern": "^[012][0-9]-[012][0-9]-[2][0][0-9][0-9] [012][0-9]:[0-5][0-9]:[0-5][0-9].[0-9]{6}$"
    },
    "opening_date": {
      "id": "#/properties/opening_date",
      "type": "string",
      "title": "Date time in UTC for when the package was opened by someone at the bulk scanning supplier premises",
      "pattern": "^[012][0-9]-[012][0-9]-[2][0][0-9][0-9] [012][0-9]:[0-5][0-9]:[0-5][0-9].[0-9]{6}$"
    },
    "zip_file_createddate": {
      "id": "#/properties/zip_file_createddate",
      "type": "string",
      "title": "Date time in UTC for when the zip file  was created at the bulk scanning supplier premises",
      "pattern": "^[012][0-9]-[012][0-9]-[2][0][0-9][0-9] [012][0-9]:[0-5][0-9]:[0-5][0-9].[0-9]{6}$"
    },
    "zip_file_name": {
      "id": "#/properties/zip_file_name",
      "type": "string",
      "title": "The name of the zip file",
      "pattern": "^\\d+_[012][0-9]-[012][0-9]-[2][0][0-9][0-9]-[012][0-9]-[0-5][0-9]-[0-5][0-9]\\.zip$"
    },
    "urgent": {
      "id": "#/properties/urgent",
      "type": "string",
      "title": "Determines if the envelope in the post is to be processed urgently. Services to provide what is classed as urgent.",
      "enum": [
        "false",
        "true"
      ],
      "default": "false"
    },
    "classification": {
      "id": "#/properties/classification",
      "type": "string",
      "enum": [
        "exception",
        "new_application",
        "supplementary_evidence"
      ],
      "default": "exception"
    },
    "scannable_items": {
      "id": "#/properties/scannable_items",
      "type": "array",
      "minItems": 1,
      "uniqueItems": true,
      "title": "Array representing items in the envelope that can be scanned for",
      "items": {
        "id": "#/properties/scannable_items/items",
        "type": "object",
        "properties": {
          "document_control_number": {
            "id": "#/properties/scannable_items/items/properties/document_control_number",
            "type": "string",
            "title": "The unique identifier for the scanned document",
            "pattern": "^[0-9]+$"
          },
          "scanning_date": {
            "id": "#/properties/scannable_items/items/properties/scanning_date",
            "type": "string",
            "title": "Date time in UTC for when the package was scanned by someone at the bulk scanning supplier premises",
            "pattern": "^[012][0-9]-[012][0-9]-[2][0][0-9][0-9] [012][0-9]:[0-5][0-9]:[0-5][0-9].[0-9]{6}$"
          },
          "ocr_accuracy": {
            "id": "#/properties/scannable_items/items/properties/ocr_accuracy",
            "type": "string",
            "title": "To be decided, if it is possible to define something that defines the level of ocr accuracy."
          },
          "manual_intervention": {
            "id": "#/properties/scannable_items/items/properties/manual_intervention",
            "type": "string",
            "title": "Description of any manual intervention that had to be done during / before the scanning."
          },
          "next_action": {
            "id": "#/properties/scannable_items/items/properties/next_action",
            "type": "string",
            "title": "Next action that the scanning supplier will be taking on the document for"
          },
          "next_action_date": {
            "id": "#/properties/scannable_items/items/properties/next_action_date",
            "type": "string",
            "title": "Date time in UTC for when the next action will occur.",
            "pattern": "^[012][0-9]-[012][0-9]-[2][0][0-9][0-9] [012][0-9]:[0-5][0-9]:[0-5][0-9].[0-9]{6}$"
          },
          "ocr_data": {
            "id": "#/properties/scannable_items/items/properties/ocr_data",
            "type": "string",
            "pattern": "^[0-9a-zA-Z=]*$"
          },
          "file_name": {
            "id": "#/properties/scannable_items/items/properties/file_name",
            "type": "string",
            "pattern": "^.+\\.pdf$"
          },
          "notes": {
            "id": "#/properties/scannable_items/items/properties/notes",
            "type": "string",
            "title": "contextual information describing the scanned file."
          },
          "document_type": {
            "id": "#/properties/scannable_items/items/properties/document_type",
            "type": "string",
            "default": "Other"
          }
        },
        "required": [
          "document_control_number",
          "scanning_date",
          "file_name",
          "document_type",
          "next_action",
          "next_action_date"
        ]
      }
    },
    "payments": {
      "id": "#/properties/payments",
      "type": "array",
      "minItems": 0,
      "uniqueItems": true,
      "title": "Array representing payments in the envelope",
      "items": {
        "id": "#/properties/payments/items",
        "type": "object",
        "properties": {
          "document_control_number": {
            "id": "#/properties/payments/items/properties/document_control_number",
            "type": "string",
            "title": "The unique identifier for the scanned document forThe uni",
            "pattern": "^[0-9]+$"
          },
          "method": {
            "id": "#/properties/payments/items/properties/method",
            "type": "string",
            "title": "The payment method"
          },
          "amount": {
            "id": "#/properties/payments/items/properties/amount",
            "type": "string",
            "title": "The payment amount",
            "pattern": "^[0-9]+\\.[0-9]{2}$"
          },
          "currency": {
            "id": "#/properties/payments/items/properties/currency",
            "type": "string",
            "title": "ISO 4217 Currency CodeISO 42",
            "pattern": "^[A-Z]{3}$"
          },
          "payment_instrument_number": {
            "id": "#/properties/payments/items/properties/payment_instrument_number",
            "type": "string",
            "title": "Cheque number in case of cheques ; postal order number in case of postal orders"
          },
          "sort_code": {
            "id": "#/properties/payments/items/properties/sort_code",
            "type": "string",
            "title": "The sort code in case of cheque payments otherwise empty"
          },
          "account_number": {
            "id": "#/properties/payments/items/properties/account_number",
            "type": "string",
            "title": "The account number in case of cheque payments otherwise empty"
          }
        },
        "required": [
          "document_control_number",
          "method",
          "amount",
          "currency"
        ]
      }
    },
    "non_scannable_items": {
      "id": "#/properties/non_scannable_items",
      "type": "array",
      "minItems": 0,
      "uniqueItems": true,
      "title": "Array representing items in the envelope that cannot be scanned",
      "items": {
        "id": "#/properties/non_scannable_items/items",
        "type": "object",
        "properties": {
          "document_control_number": {
            "id": "#/properties/non_scannable_items/items/properties/document_control_number",
            "type": "string",
            "title": "The unique identifier for the scanned document for the no",
            "pattern": "^[0-9]+$"
          },
          "item_type": {
            "id": "#/properties/non_scannable_items/items/properties/item_type",
            "type": "string",
            "title": "CD, DVD, USB memory stick"
          },
          "notes": {
            "id": "#/properties/non_scannable_items/items/properties/notes",
            "type": "string",
            "title": "contextual information describing this item"
          }
        },
        "required": [
          "document_control_number",
          "item_type"
        ]
      }
    }
  },
  "required": [
    "po_box",
    "jurisdiction",
    "delivery_date",
    "opening_date",
    "zip_file_createddate",
    "zip_file_name",
    "urgent",
    "classification",
    "scannable_items"
  ]
}

=== hmcts/bulk-scan-processor/src/test/resources/metafiles/valid/cash-payment-method.json
{
  "case_number": "1111222233334446",
  "po_box": "XXXX",
  "jurisdiction": "SSCS",
  "delivery_date": "23-02-2017 00:00:00.100000",
  "opening_date": "24-02-2017 00:00:00.010000",
  "zip_file_createddate": "24-02-2017 00:00:00.001000",
  "zip_file_name": "1_24-02-2017-00-00-00.zip",
  "urgent": "false",
  "classification": "new_application",
  "scannable_items": [
    {
      "document_control_number": "1111001",
      "scanning_date": "24-02-2017 00:00:00.000001",
      "manual_intervention": "string",
      "next_action": "forward",
      "next_action_date": "25-02-2017 00:00:00.000000",
      "file_name": "1111001.pdf",
      "notes": "test",
      "document_type": "Other"
    },
    {
      "document_control_number": "1111002",
      "scanning_date": "24-02-2017 00:00:00.000001",
      "manual_intervention": "string",
      "next_action": "forward",
      "next_action_date": "25-02-2017 00:00:00.000000",
      "file_name": "1111002.pdf",
      "notes": "Cheque will be forwarded to court to bank it",
      "document_type": "Other"
    }
  ],
  "payments": [
    {
      "document_control_number": "1111002",
      "method": "Cash",
      "amount": "100.00",
      "currency": "GBP"
    }
  ],
  "non_scannable_items": [
    {
      "document_control_number": "1111001",
      "item_type": "CD",
      "notes": "4GB USB memory stick"
    }
  ]
}
